### PR TITLE
home work

### PR DESCRIPTION
**Pull request by gyrydymptum**
authors: @gyrydymptum , @Lukasz-334

### CODE REVIEW

**Comment by ziobron** [comment]
✅ CI Passed - Task: debuggers
🏅 Granted 10 XP for @gyrydymptum

**Comment by ziobron** [comment]
⏱ 3 XP extra for @gyrydymptum for on-time delivery

**Comment by ziobron** [comment]
🏅 +1 XP for cooperation goes to @gyrydymptum

**Comment by ziobron** [comment]
✅ CI Passed - Task: debuggers
🏅 Granted 10 XP for @Lukasz-334

**Comment by ziobron** [comment]
⏱ 3 XP extra for @Lukasz-334 for on-time delivery

**Comment by ziobron** [comment]
🏅 +1 XP for cooperation goes to @Lukasz-334

**Comment by Mati365** [comment]
+10 pkt dla Gryffindoru

**Review by lukasz-kukulka — APPROVED** [review]

**Comment by ziobron** [comment]
Thanks @lukasz-kukulka for Code Review.
🏅 1 XP granted

**Review by nauka-programowania-MA — APPROVED** [review]

**Pull request closed without merging**
