### PR TITLE
errors fixed with debugger

### PR DESCRIPTION
**Pull request by piotrku91**

### CODE REVIEW

**Comment by ziobron** [comment]
✅ CI Passed - Task: debuggers
🏅 Granted 10 XP for @piotrku91

**Comment by ziobron** [comment]
⏱ 3 XP extra for @piotrku91 for on-time delivery

**Review by gyrydymptum — COMMENTED** [review]
correct

**Comment by ziobron** [comment]
Thanks @gyrydymptum for Code Review.
🏅 1 XP granted

**Pull request closed without merging**
