### PR TITLE
Homework

### PR DESCRIPTION
**Pull request by raxonpc**

### CODE REVIEW

**Comment by ziobron** [comment]
✅ CI Passed - Task: debuggers
🏅 Granted 10 XP for @raxonpc

**Comment by ziobron** [comment]
⏱ 3 XP extra for @raxonpc for on-time delivery

**Review by gyrydymptum — COMMENTED** [review]
correct

**Comment by ziobron** [comment]
Thanks @gyrydymptum for Code Review.
🏅 1 XP granted

**Pull request closed without merging**
