### PR TITLE
Pizzas -gdb - removed bugs

### PR DESCRIPTION
**Pull request by Martyna-Tu**

### CODE REVIEW

**Comment by ziobron** [comment]
✅ CI Passed - Task: debuggers
🏅 Granted 10 XP for @Martyna-Tu

**Comment by ziobron** [comment]
⏱ 3 XP extra for @Martyna-Tu for on-time delivery

**Review by lukasz-kukulka — APPROVED** [review]

**Comment by ziobron** [comment]
Thanks @lukasz-kukulka for Code Review.
🏅 1 XP granted

**Review by gyrydymptum — APPROVED** [review]

**Comment by ziobron** [comment]
Thanks @gyrydymptum for Code Review.
🏅 1 XP granted

**Review by nauka-programowania-MA — APPROVED** [review]

**Pull request closed without merging**
