### PR TITLE
Homework  debuggers, pizzas 

### PR DESCRIPTION
**Pull request by Warp-12**
Authors: @BarTes8, @Warp-12 \n Find 3 bugs, all tests passed.

### CODE REVIEW

**Comment by ziobron** [comment]
✅ CI Passed - Task: debuggers
🏅 Granted 10 XP for @BarTes8

**Comment by ziobron** [comment]
⏱ 3 XP extra for @BarTes8 for on-time delivery

**Comment by ziobron** [comment]
🏅 +1 XP for cooperation goes to @BarTes8

**Comment by ziobron** [comment]
✅ CI Passed - Task: debuggers
🏅 Granted 10 XP for @Warp-12

**Comment by ziobron** [comment]
⏱ 3 XP extra for @Warp-12 for on-time delivery

**Comment by ziobron** [comment]
🏅 +1 XP for cooperation goes to @Warp-12

**Review by nauka-programowania-MA — APPROVED** [review]

**Pull request closed without merging**
