### PR TITLE
Homework pizzas debugging

### PR DESCRIPTION
**Pull request by lukasz-kukulka**

### CODE REVIEW

**Comment by ziobron** [comment]
✅ CI Passed - Task: debuggers
🏅 Granted 10 XP for @lukasz-kukulka

**Comment by ziobron** [comment]
⏱ 3 XP extra for @lukasz-kukulka for on-time delivery

**Review by gyrydymptum — APPROVED** [review]

**Comment by ziobron** [comment]
Thanks @gyrydymptum for Code Review.
🏅 1 XP granted

**Review by gyrydymptum — APPROVED** [review]

**Comment by ziobron** [comment]
Thanks @gyrydymptum for Code Review.
🏅 1 XP granted

**Review by nauka-programowania-MA — APPROVED** [review]

**Pull request closed without merging**
